# Generated by Django 4.0.2 on 2023-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
